#!/usr/bin/env python3
import argparse,csv,json,hashlib
from pathlib import Path
import numpy as np,torch
from ccda_phase3.phase314a_contract import Standardizer,strict_json_dump
from ccda_phase3.phase314b_r21_geometry import calibrated_validity
from ccda_phase3.phase314b_r22_contract import *
from ccda_phase3.phase314b_r22_geometry import *
from scripts.phase3_14a_train_deterministic import FutureMLP

def metrics(name,pred,target,contract):
 validity=calibrated_validity(pred[None],contract); ordered=final_ordered_rmse_pool(pred[None],target)[0]; xy=pred[...,:48].reshape(-1,4,24,2); txy=target[...,:48].reshape(-1,4,24,2); seg=np.linalg.norm(xy[...,1:,:]-xy[...,:-1,:],axis=-1); tseg=np.linalg.norm(txy[...,1:,:]-txy[...,:-1,:],axis=-1); inv=nearest_index_metrics(pred,target)['nearest_inversion']; return {'reference':name,'rows':len(pred),'calibrated_validity':validity['sample_validity_rate'],'coordinate_validity':validity['coordinate_validity_rate'],'segment_validity':validity['segment_score_validity_rate'],'chain_validity':validity['chain_score_validity_rate'],'quaternion_validity':validity['quaternion_validity_rate'],'final_ordered_rmse':float(ordered.mean()),'trajectory_ordered_rmse':float(np.sqrt(np.mean((pred[...,:48]-target[...,:48])**2))),'gross_stretch_fraction':float(np.mean(seg/np.maximum(tseg,1e-8)>=4)),'gross_compression_fraction':float(np.mean(seg/np.maximum(tseg,1e-8)<=.25)),'nearest_inversion':float(inv.mean())}
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--root',default='/data/state_diff2'); a=ap.parse_args(); root=Path(a.root); frozen=load_self_hashed_json(root/'reports/phase3_14b_r22_frozen_contract.json'); arrays,manifest,x,xs,tr,fit,cal,val=load_train_validation_rows(root); physical=contract_from_json(frozen['physical_contract']); target=arrays['y_state']; repeat=last_repeat_future(arrays['paper_x'][val]); sel=json.loads((root/'reports/phase3_14a_selected_deterministic_model.json').read_text()); cp=torch.load(root/sel['checkpoint'],map_location='cpu');
 if cp.get('input_variant')!='state_action' or cp.get('cache_sha256')!=CACHE_SHA256: raise RuntimeError('deterministic checkpoint contract mismatch')
 std=Standardizer(np.asarray(arrays['state_action_x_mean'],np.float32),np.asarray(arrays['state_action_x_scale'],np.float32),np.asarray(arrays['state_action_x_active'],bool),np.asarray(arrays['state_action_x_raw_std'],np.float32)); model=FutureMLP.create(303); model.load_state_dict(cp['model_state_dict']); model.eval(); inp=torch.from_numpy(std.transform(arrays['state_action_x'][val])).float(); predz=model(inp).detach().numpy().reshape(-1,4,87); fstd=Standardizer(np.asarray(arrays['future_mean'],np.float32),np.asarray(arrays['future_scale'],np.float32),np.asarray(arrays['future_active'],bool),np.asarray(arrays['future_raw_std'],np.float32)); det=fstd.inverse(predz)
 rows=[metrics('train_fit_gt',target[fit],target[fit],physical),metrics('train_calibration_gt',target[cal],target[cal],physical),metrics('validation_gt',target[val],target[val],physical),metrics('validation_last_repeat',repeat,target[val],physical),metrics('validation_deterministic_mlp',det,target[val],physical)]; out=root/'reports/phase3_14b_r22_reference_geometry.csv'; fields=sorted({k for r in rows for k in r}); out.parent.mkdir(exist_ok=True); h=out.open('w',newline=''); w=csv.DictWriter(h,fieldnames=fields); w.writeheader(); w.writerows(rows); h.close(); summary={'verdict':'PASS','root_cause':'phase314b_r22_reference_audit_supported','deterministic_input_variant':'state_action','references':rows,'formal_test_read':False}; strict_json_dump(root/'reports/phase3_14b_r22_reference_audit_summary.json',summary); (root/'reports/phase3_14b_r22_reference_audit_report.md').write_text('# Phase3.14b-r2.2 Reference Audit\n\n- Verdict: `PASS`\n- Deterministic input: `state_action`\n- Formal test read: `False`\n'); print(json.dumps(summary,indent=2))
if __name__=='__main__': main()
