#!/usr/bin/env python3
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
from ccda_phase3.phase314a_contract import sha256_file,strict_json_dump
from ccda_phase3.phase314b_contract import CACHE_SHA256
from ccda_phase3.phase314b_r21_geometry import fit_calibrated_geometry_contract,calibrated_validity
from ccda_phase3.phase314b_r22_contract import *
from ccda_phase3.phase314b_r22_geometry import *
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--root',default='/data/state_diff2'); a=ap.parse_args(); root=Path(a.root).resolve(); arrays,manifest,x,xs,tr,fit,cal,val=load_train_validation_rows(root); assert_no_test_access(arrays,tr,val)
 future=np.asarray(arrays['y_state'],np.float32); physical=fit_calibrated_geometry_contract(fit_future=future[fit],calibration_future=future[cal]); norms=fit_geometry_normalizers(future[fit]); cal_repeat=last_repeat_future(arrays['paper_x'][cal]); thresholds=fit_prediction_reference_thresholds(cal_repeat,future[cal],alpha=.10); val_repeat=last_repeat_future(arrays['paper_x'][val]); coverage={'fit_gt':calibrated_validity(future[fit][None],physical)['sample_validity_rate'],'calibration_gt':calibrated_validity(future[cal][None],physical)['sample_validity_rate'],'validation_gt':calibrated_validity(future[val][None],physical)['sample_validity_rate'],'last_repeat_validation':calibrated_validity(val_repeat[None],physical)['sample_validity_rate']}
 if coverage['validation_gt']<.90 or coverage['last_repeat_validation']<.95: raise RuntimeError('reference coverage gate failed')
 payload={'artifact_version':'phase3_14b_r22_frozen_contract_v1','phase':PHASE,'created_at':datetime.now(timezone.utc).isoformat(),'base_main_commit':BASE_MAIN_COMMIT,'implementation_commit':git_commit(root),'submodule_commit':SUBMODULE_COMMIT,'cache_path':'data/phase3_14_cache/phase3_14a_training_cache.npz','cache_sha256':CACHE_SHA256,'cache_manifest_sha256':sha256_file(root/'data/phase3_14_cache/phase3_14a_training_cache_manifest.json'),'model_family':MODEL_FAMILY,'input_variant':INPUT_VARIANT,'repair_config':REPAIR_CONFIG_NAME,'num_train_timesteps':100,'diffusers_version':'0.11.1','train_row_count':len(tr),'fit_row_count':len(fit),'calibration_row_count':len(cal),'validation_row_count':len(val),'validation_pair_key_count':len(np.unique(arrays['pair_key'][val].astype(str))),'fit_visible_seeds':sorted(np.unique(arrays['visible_seed'][fit]).astype(int).tolist()),'calibration_visible_seeds':sorted(np.unique(arrays['visible_seed'][cal]).astype(int).tolist()),'validation_visible_seeds':sorted(np.unique(arrays['visible_seed'][val]).astype(int).tolist()),'physical_contract':{**physical.to_json(),'calibration_alpha':.01},'geometry_normalizers':norms.to_json(),'prediction_reference_contract':thresholds,'reference_coverage':coverage,'checkpoint_bound_source_sha256':source_sha256(root),'formal_test_read':False,'formal_test_run':False,'idm':False,'candidate_execution':False,'phase4':False,'cps':False}; frozen=write_self_hashed_json(root/'reports/phase3_14b_r22_frozen_contract.json',payload); summary={'verdict':'PASS','root_cause':'phase314b_r22_frozen_contract_supported','artifact_sha256':frozen['artifact_sha256'],'reference_coverage':coverage,'formal_test_read':False}; strict_json_dump(root/'reports/phase3_14b_r22_contract_summary.json',summary); (root/'reports/phase3_14b_r22_contract_report.md').write_text(f"# Phase3.14b-r2.2 Frozen Contract\n\n- Verdict: `PASS`\n- SHA256: `{frozen['artifact_sha256']}`\n- Formal test read: `False`\n"); print(json.dumps(summary,indent=2))
if __name__=='__main__': main()
