#!/usr/bin/env python3
"""Fresh v-prediction MLP training with differentiable ordered geometry."""
import argparse,csv,json,os,random,time
from pathlib import Path
import numpy as np,torch
from ccda_phase3.phase314a_contract import sha256_file,strict_json_dump
from ccda_phase3.phase314b_contract import future_standardizer
from ccda_phase3.phase314b_diffusion import ExponentialMovingAverage
from ccda_phase3.phase314b_models import build_denoiser,parameter_count
from ccda_phase3.phase314b_r2_contract import REPAIR_CONFIGS
from ccda_phase3.phase314b_r2_diffusion import make_repair_scheduler,sample_future_z,partial_denoise
from ccda_phase3.phase314b_r22_contract import *
from ccda_phase3.phase314b_r22_geometry import *
from ccda_phase3.phase314b_r22_loss import geometry_aware_v_loss

def seed_all(s): random.seed(s);np.random.seed(s);torch.manual_seed(s);torch.cuda.manual_seed_all(s);torch.backends.cudnn.deterministic=True;torch.backends.cudnn.benchmark=False
def csv_write(p,rows):
 f=sorted({k for r in rows for k in r});h=Path(p).open('w',newline='');w=csv.DictWriter(h,fieldnames=f);w.writeheader();w.writerows(rows);h.close()
def eval_pool(model,xz,rows,target,fstd,active,physical,frozen,device,k,seed):
 config=REPAIR_CONFIGS['v_prediction_cosine']; z=sample_future_z(model=model,scheduler=make_repair_scheduler(config),config=config,condition_z=torch.from_numpy(xz[rows]).float().to(device),active_mask=torch.from_numpy(active).to(device),num_samples=k,seed=seed,num_inference_steps=100,row_batch_size=128).numpy().astype(np.float32); raw=fstd.inverse(z); m=evaluate_validation_pool(z,raw,target[rows],physical,float(frozen['prediction_reference_contract']['final_ordered_rmse_threshold']),float(frozen['prediction_reference_contract']['nearest_index_inversion_threshold'])); return m,z,raw
def partial(model,xz,yz,target,rows,fstd,active,device,t,seed):
 c=REPAIR_CONFIGS['v_prediction_cosine']; z=partial_denoise(model=model,scheduler=make_repair_scheduler(c),config=c,clean_z=torch.from_numpy(yz[rows]).float().to(device),condition_z=torch.from_numpy(xz[rows]).float().to(device),active_mask=torch.from_numpy(active).to(device),start_timestep=t,seed=seed).numpy(); raw=fstd.inverse(z); p=raw[:,-1,:48].reshape(-1,24,2); q=target[rows,-1,:48].reshape(-1,24,2); return float(np.mean(np.sqrt(np.mean((p-q)**2,axis=(1,2)))))
def moderate(m,t99):
 c=m['calibrated']; checks={'finite':m['finite'],'sample':c['sample_validity_rate']>=.50,'query':c['query_has_valid_candidate_rate']>=.75,'coordinate':c['coordinate_validity_rate']>=.80,'segment':c['segment_score_validity_rate']>=.50,'chain':c['chain_score_validity_rate']>=.50,'quaternion':c['quaternion_validity_rate']>=.95,'stretch_fraction':m['gross_stretch_fraction']<=.05,'compression_fraction':m['gross_compression_fraction']<=.05,'stretch_p95':m['segment_stretch_p95']<=8,'permutation':m['permutation_gap']<=.05,'ordered_support':m['ordered_support_rate']>=.50,'diversity':m['pool_diversity']>=.001,'z99':m['z_abs_p99']<=10,'zmax':m['z_abs_max']<=50,'t99':t99<=.35}; return {'pass':all(checks.values()),'checks':checks}
def formal_gate(m,t10,t99,improvement_ci):
 c=m['calibrated']; checks={'finite':m['finite'],'sample':c['sample_validity_rate']>=.90,'query':c['query_has_valid_candidate_rate']>=.95,'coordinate':c['coordinate_validity_rate']>=.95,'segment':c['segment_score_validity_rate']>=.90,'chain':c['chain_score_validity_rate']>=.90,'quaternion':c['quaternion_validity_rate']>=.99,'stretch_fraction':m['gross_stretch_fraction']<=.01,'compression_fraction':m['gross_compression_fraction']<=.01,'stretch_p95':m['segment_stretch_p95']<=4,'z99':m['z_abs_p99']<=10,'zmax':m['z_abs_max']<=50,'t10':t10<=0.060045241308651624,'t99':t99<=.25,'k1':m['k1_chamfer']<=.25,'best8':m['best8_chamfer']<=.12,'ordered_support':m['ordered_support_rate']>=.90,'ordered_rmse':m['best8_ordered_rmse']<=0,'permutation':m['permutation_gap']<=.02,'inversion':m['nearest_inversion_p95']<=0,'diversity':m['pool_diversity']>=.003,'improvement_ci':improvement_ci>0}; return checks
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--root',default='/data/state_diff2');ap.add_argument('--mode',choices=['pilot','formal'],required=True);ap.add_argument('--configs',nargs='+');ap.add_argument('--seeds',nargs='+',type=int);ap.add_argument('--max-epochs',type=int,default=750);ap.add_argument('--batch-size',type=int,default=128);a=ap.parse_args();root=Path(a.root);frozen=load_self_hashed_json(root/'reports/phase3_14b_r22_frozen_contract.json'); arrays,manifest,xraw,xstd,tr,fit,cal,val=load_train_validation_rows(root);assert_no_test_access(arrays,tr,val)
 if os.environ.get('PHASE314B_R22_REQUIRE_CUDA')=='1' and not torch.cuda.is_available():
  raise RuntimeError('CUDA required')
 device=torch.device('cuda' if torch.cuda.is_available() else 'cpu'); active=np.asarray(arrays['future_active'],bool); assert active.shape==(4,87) and active[:,:48].all(); xz=xstd.transform(xraw);fstd=future_standardizer(arrays);yz=fstd.transform(arrays['y_state']);target=np.asarray(arrays['y_state'],np.float32);physical=contract_from_json(frozen['physical_contract']);norms=normalizers_from_json(frozen['geometry_normalizers']); config=REPAIR_CONFIGS['v_prediction_cosine']; configs=a.configs or (list(GEOMETRY_CONFIGS) if a.mode=='pilot' else [load_self_hashed_json(root/'reports/phase3_14b_r22_pilot_selection.json')['selected_config']]); seeds=a.seeds or ([PILOT_SEED] if a.mode=='pilot' else list(FORMAL_SEEDS)); history=[];runs=[]; xt=torch.from_numpy(xz[tr]).float();yt=torch.from_numpy(yz[tr]).float();yr=torch.from_numpy(target[tr]).float(); mean=torch.from_numpy(np.asarray(arrays['future_mean'],np.float32)).to(device);scale=torch.from_numpy(np.asarray(arrays['future_scale'],np.float32)).to(device);at=torch.from_numpy(active).to(device)
 for cname in configs:
  gc=GEOMETRY_CONFIGS[cname]
  for seed in seeds:
   seed_all(seed);model=build_denoiser('mlp_ddpm',condition_dim=261).to(device);opt=torch.optim.AdamW(model.parameters(),lr=3e-4,weight_decay=1e-4);ema=ExponentialMovingAverage(model,.999);scheduler=make_repair_scheduler(config);pg=torch.Generator().manual_seed(seed);dg=torch.Generator(device=device).manual_seed(seed+100000);best=None;bestkey=None;stale=0
   for epoch in range(1,a.max_epochs+1):
    model.train();perm=torch.randperm(len(tr),generator=pg); accum={}
    for start in range(0,len(tr),a.batch_size):
     bi=perm[start:start+a.batch_size];cond=xt[bi].to(device);clean=yt[bi].to(device);raw=yr[bi].to(device);ts=torch.randint(0,100,(len(bi),),generator=dg,device=device);noise=torch.randn(clean.shape,generator=dg,device=device);noise=torch.where(at[None],noise,torch.zeros_like(noise));noisy=scheduler.add_noise(clean,noise,ts);noisy=torch.where(at[None],noisy,torch.zeros_like(noisy));out=model(noisy,ts,cond);out=torch.where(at[None],out,torch.zeros_like(out));losses=geometry_aware_v_loss(model_output=out,noisy_sample=noisy,clean_z=clean,clean_raw=raw,noise=noise,timesteps=ts,scheduler=scheduler,repair_config=config,active_mask=at,future_mean=mean,future_scale=scale,normalizers=norms,geometry_config=gc,epoch=epoch-1);opt.zero_grad();losses['total_loss'].backward();before=float(torch.nn.utils.clip_grad_norm_(model.parameters(),1.0));opt.step();ema.update(model);accum.setdefault('total',[]).append(float(losses['total_loss'].detach()))
    if epoch%25: continue
    em=ema.averaged_model(model,device=device);m,_,_=eval_pool(em,xz,val,target,fstd,active,physical,frozen,device,4,394000);key=(-m['calibrated']['sample_validity_rate'],-m['calibrated']['segment_score_validity_rate'],-m['ordered_support_rate'],m['best8_ordered_rmse'],m['best8_chamfer'],-m['pool_diversity']);history.append({'mode':a.mode,'config':cname,'seed':seed,'epoch':epoch,'total_loss':np.mean(accum['total']),'sample_validity':m['calibrated']['sample_validity_rate'],'ordered_support':m['ordered_support_rate'],'best4_chamfer':m['best8_chamfer']})
    if bestkey is None or key<bestkey: bestkey=key;best=(epoch,{k:v.cpu().clone() for k,v in model.state_dict().items()},ema.state_dict());stale=0
    else: stale+=1
    if stale>=8: break
   epoch,state,emastate=best;model.load_state_dict(state);em=ExponentialMovingAverage.from_state_dict(model,emastate).averaged_model(model,device=device);m,z,raw=eval_pool(em,xz,val,target,fstd,active,physical,frozen,device,8,396000 if a.mode=='formal' else 394000);t10=partial(em,xz,yz,target,val[:16],fstd,active,device,10,395010);t99=partial(em,xz,yz,target,val[:16],fstd,active,device,99,395099 if a.mode=='formal' else 395000);mg=moderate(m,t99)
   ordered_k1=final_ordered_rmse_pool(raw[:1],target[val])[0];repeat=last_repeat_future(arrays['paper_x'][val]);repeat_err=final_ordered_rmse_pool(repeat[None],target[val])[0];imp=repeat_err-ordered_k1; rng=np.random.default_rng(77);seedsv=np.asarray(arrays['visible_seed'][val]);u=np.unique(seedsv);boots=[]
   for _ in range(10000): sample=rng.choice(u,len(u),replace=True);boots.append(np.mean([np.mean(imp[seedsv==s]) for s in sample]));ci=float(np.percentile(boots,2.5));fg=formal_gate(m,t10,t99,ci);fg['ordered_rmse']=m['best8_ordered_rmse']<=float(frozen['prediction_reference_contract']['final_ordered_rmse_threshold']);fg['inversion']=m['nearest_inversion_p95']<=float(frozen['prediction_reference_contract']['nearest_index_inversion_threshold']);stable=all(fg.values())
   cp=root/f'checkpoints/phase3_14b_r22/{a.mode}/{cname}/seed_{seed}/best.pt';payload={'phase':PHASE,'mode':a.mode,'geometry_config':cname,'training_seed':seed,'best_epoch':epoch,'cache_sha256':CACHE_SHA256,'frozen_contract_sha256':frozen['artifact_sha256'],'source_sha256':source_sha256(root),'formal_test_read':False,'model_state_dict':state,'ema_state_dict':emastate};strict_checkpoint_save(cp,payload);runs.append({'mode':a.mode,'geometry_config':cname,'training_seed':seed,'best_epoch':epoch,'checkpoint':str(cp.relative_to(root)),'checkpoint_sha256':sha256_file(cp),'metrics':m,'partial_t10_chamfer':t10,'partial_t99_chamfer':t99,'moderate_gate':mg,'formal_checks':fg,'stable':stable,'ordered_improvement_ci_low':ci})
 summary={'verdict':'PASS','root_cause':f'phase314b_r22_{a.mode}_training_completed','mode':a.mode,'device':str(device),'run_count':len(runs),'runs':runs,'formal_test_read':False,'idm':False,'candidate_execution':False,'phase4':False,'cps':False};prefix=f'phase3_14b_r22_{a.mode}_training';strict_json_dump(root/f'reports/{prefix}_summary.json',summary);csv_write(root/f'reports/{prefix}_history.csv',history);(root/f'reports/{prefix}_report.md').write_text(f'# Phase3.14b-r2.2 {a.mode.title()} Training\n\n- Runs: `{len(runs)}`\n- Formal test read: `False`\n');print(json.dumps({'runs':len(runs),'stable':sum(r['stable'] for r in runs)},indent=2))
if __name__=='__main__':main()
