#!/usr/bin/env python3
"""Phase2 CCDA audit for hidden-contact cable-line.

This script audits paired rollouts generated by DeformableRavens
hidden-contact-cable-line.

It checks whether pairs with similar visible state and similar action history
but different hidden contact conditions diverge in future cable state and
success outcome.

Expected data layout:

data_root/
  free/
    color/*.pkl
    depth/*.pkl
    action/*.pkl
    info/*.pkl
    last_info/*.pkl
  hidden_pin/
  hidden_high_friction/
"""

import argparse
import csv
import gc
import json
import math
import pickle
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import numpy as np


CONDITIONS = ["free", "hidden_pin", "hidden_high_friction"]


def load_pickle(path: Path) -> Any:
    with path.open("rb") as f:
        return pickle.load(f)


def as_float(x: Any) -> Optional[float]:
    try:
        if x is None:
            return None
        v = float(x)
        if math.isnan(v) or math.isinf(v):
            return None
        return v
    except Exception:
        return None


def fmt(x: Any, digits: int = 4) -> str:
    v = as_float(x)
    if v is None:
        return "NA"
    return f"{v:.{digits}f}"


def mean(xs: Iterable[Any]) -> Optional[float]:
    vals = [as_float(x) for x in xs]
    vals = [x for x in vals if x is not None]
    if not vals:
        return None
    return float(np.mean(vals))


def std(xs: Iterable[Any]) -> Optional[float]:
    vals = [as_float(x) for x in xs]
    vals = [x for x in vals if x is not None]
    if len(vals) < 2:
        return 0.0 if len(vals) == 1 else None
    return float(np.std(vals))


def get_extras(info: Dict) -> Dict:
    if isinstance(info, dict):
        ex = info.get("extras", {})
        if isinstance(ex, dict):
            return ex
    return {}


def get_bead_positions(info: Dict) -> Optional[np.ndarray]:
    """Extract ordered bead xyz positions from info or info['extras']."""
    ex = get_extras(info)

    if "bead_positions" in ex:
        arr = np.asarray(ex["bead_positions"], dtype=np.float32)
        if arr.ndim == 2 and arr.shape[1] >= 3:
            return arr[:, :3]

    if "bead_ids" in ex:
        pos = []
        for bid in ex["bead_ids"]:
            if bid in info:
                v = info[bid]
                if isinstance(v, tuple) and len(v) >= 1:
                    pos.append(v[0])
        if pos:
            arr = np.asarray(pos, dtype=np.float32)
            if arr.ndim == 2 and arr.shape[1] >= 3:
                return arr[:, :3]

    int_keys = sorted(k for k in info.keys() if isinstance(k, int))
    pos = []
    for k in int_keys:
        v = info[k]
        if isinstance(v, tuple) and len(v) >= 1:
            p = v[0]
            if hasattr(p, "__len__") and len(p) == 3:
                pos.append(p)
    if pos:
        arr = np.asarray(pos, dtype=np.float32)
        if arr.ndim == 2 and arr.shape[1] >= 3:
            return arr[:, :3]

    return None


def curve_metric(beads: Optional[np.ndarray]) -> Optional[float]:
    if beads is None or len(beads) < 3:
        return None
    xy = beads[:, :2]
    second = xy[:-2] - 2.0 * xy[1:-1] + xy[2:]
    return float(np.mean(np.linalg.norm(second, axis=1)))


def chamfer_xy(a: Optional[np.ndarray], b: Optional[np.ndarray]) -> Optional[float]:
    if a is None or b is None:
        return None
    a = np.asarray(a, dtype=np.float32)[:, :2]
    b = np.asarray(b, dtype=np.float32)[:, :2]
    if len(a) == 0 or len(b) == 0:
        return None
    d2 = ((a[:, None, :] - b[None, :, :]) ** 2).sum(axis=2)
    return float(np.mean(np.sqrt(d2.min(axis=1))) + np.mean(np.sqrt(d2.min(axis=0))))


def ordered_l2_xy(a: Optional[np.ndarray], b: Optional[np.ndarray]) -> Optional[float]:
    if a is None or b is None:
        return None
    a = np.asarray(a, dtype=np.float32)[:, :2]
    b = np.asarray(b, dtype=np.float32)[:, :2]
    n = min(len(a), len(b))
    if n == 0:
        return None
    return float(np.mean(np.linalg.norm(a[:n] - b[:n], axis=1)))


def flatten_numeric(obj: Any) -> List[float]:
    """Recursively flatten numeric action fields into a vector."""
    out: List[float] = []

    if obj is None:
        return out

    if isinstance(obj, (int, float, np.integer, np.floating)):
        v = float(obj)
        if math.isfinite(v):
            out.append(v)
        return out

    if isinstance(obj, np.ndarray):
        arr = obj.astype(np.float64).ravel()
        return [float(x) for x in arr if math.isfinite(float(x))]

    if isinstance(obj, (list, tuple)):
        for x in obj:
            out.extend(flatten_numeric(x))
        return out

    if isinstance(obj, dict):
        for k in sorted(obj.keys(), key=lambda x: str(x)):
            # Skip non-geometric string identifiers.
            if str(k) in {"primitive"}:
                continue
            out.extend(flatten_numeric(obj[k]))
        return out

    return out


def action_distance(a: Any, b: Any) -> Optional[float]:
    va = np.asarray(flatten_numeric(a), dtype=np.float32)
    vb = np.asarray(flatten_numeric(b), dtype=np.float32)

    if va.size == 0 or vb.size == 0:
        return None

    n = min(va.size, vb.size)
    return float(np.linalg.norm(va[:n] - vb[:n]) / max(1, n))


def action_history_distance(actions_a: List[Any], actions_b: List[Any], prefix_actions: int = 1) -> Optional[float]:
    n = min(len(actions_a), len(actions_b), prefix_actions)
    if n <= 0:
        return None
    vals = [action_distance(actions_a[i], actions_b[i]) for i in range(n)]
    vals = [v for v in vals if v is not None]
    if not vals:
        return None
    return float(np.mean(vals))


def select_initial_color_frame(color_obj: Any, camera_index: int = 0) -> np.ndarray:
    arr = np.asarray(color_obj)
    if arr.ndim == 5:
        # (T, C, H, W, 3)
        c = min(max(camera_index, 0), arr.shape[1] - 1)
        frame = arr[0, c]
    elif arr.ndim == 4:
        if arr.shape[-1] == 3 and arr.shape[0] <= 8:
            # (C, H, W, 3)
            c = min(max(camera_index, 0), arr.shape[0] - 1)
            frame = arr[c]
        elif arr.shape[-1] == 3:
            # (T, H, W, 3)
            frame = arr[0]
        else:
            raise ValueError(f"Unsupported color shape: {arr.shape}")
    elif arr.ndim == 3 and arr.shape[-1] == 3:
        frame = arr
    else:
        raise ValueError(f"Unsupported color shape: {arr.shape}")
    return np.array(frame, dtype=np.float32, copy=True)


def select_initial_depth_frame(depth_obj: Any, camera_index: int = 0) -> np.ndarray:
    arr = np.asarray(depth_obj)
    if arr.ndim == 4:
        # (T, C, H, W)
        c = min(max(camera_index, 0), arr.shape[1] - 1)
        frame = arr[0, c]
    elif arr.ndim == 3:
        if arr.shape[0] <= 8:
            # (C, H, W)
            c = min(max(camera_index, 0), arr.shape[0] - 1)
            frame = arr[c]
        else:
            # (T, H, W)
            frame = arr[0]
    elif arr.ndim == 2:
        frame = arr
    else:
        raise ValueError(f"Unsupported depth shape: {arr.shape}")
    return np.array(frame, dtype=np.float32, copy=True)


def load_initial_color_for_episode(ep: Dict) -> np.ndarray:
    return select_initial_color_frame(load_pickle(Path(ep["color_path"])))


def load_initial_depth_for_episode(ep: Dict) -> np.ndarray:
    return select_initial_depth_frame(load_pickle(Path(ep["depth_path"])))


def arr_stats_absdiff(a: Any, b: Any) -> Dict[str, Optional[float]]:
    try:
        aa = np.asarray(a, dtype=np.float32)
        bb = np.asarray(b, dtype=np.float32)

        if aa.shape != bb.shape:
            return {
                "shape_equal": False,
                "mean_abs": None,
                "max_abs": None,
            }

        valid = np.isfinite(aa) & np.isfinite(bb)
        if aa.ndim == 2:
            valid = valid & (aa > 0) & (bb > 0)
        if not np.any(valid):
            return {
                "shape_equal": True,
                "mean_abs": None,
                "max_abs": None,
            }

        diff = np.abs(aa[valid] - bb[valid])

        return {
            "shape_equal": True,
            "mean_abs": float(np.mean(diff)),
            "max_abs": float(np.max(diff)),
        }
    except Exception:
        return {
            "shape_equal": False,
            "mean_abs": None,
            "max_abs": None,
        }


def get_episode_files(cond_dir: Path) -> List[Path]:
    color_dir = cond_dir / "color"
    if not color_dir.exists():
        return []
    return sorted(color_dir.glob("*.pkl"))


def parse_ep_len(path: Path) -> int:
    try:
        return int(path.stem.split("-")[-1])
    except Exception:
        return -1


def load_episode(cond: str, cond_dir: Path, color_file: Path) -> Dict:
    fname = color_file.name

    info_list = load_pickle(cond_dir / "info" / fname)
    last_info = load_pickle(cond_dir / "last_info" / fname)
    actions = load_pickle(cond_dir / "action" / fname)
    # RGB-D observations are intentionally loaded lazily per pair. The formal
    # Phase2 data includes 150 saved rollouts, and holding all color/depth arrays
    # in memory is unnecessary for the leakage audit.
    color_path = cond_dir / "color" / fname
    depth_path = cond_dir / "depth" / fname

    first_info = info_list[0] if info_list else {}
    first_ex = get_extras(first_info)
    last_ex = get_extras(last_info)

    first_beads = get_bead_positions(first_info)
    last_beads = get_bead_positions(last_info)

    traj = []
    for info in info_list:
        b = get_bead_positions(info)
        if b is not None:
            traj.append(b)
    last_b = get_bead_positions(last_info)
    if last_b is not None:
        traj.append(last_b)

    nb_beads = last_ex.get("nb_beads", None)
    nb_zone = last_ex.get("nb_zone", None)

    final_fraction = None
    if nb_beads:
        final_fraction = float(nb_zone) / float(nb_beads)
    elif "total_rewards" in last_ex:
        final_fraction = last_ex.get("total_rewards")

    visible_seed = first_ex.get("ccda_visible_seed", last_ex.get("ccda_visible_seed", None))
    pair_group = first_ex.get("ccda_pair_group", last_ex.get("ccda_pair_group", ""))

    return {
        "condition": cond,
        "file": fname,
        "episode_len": parse_ep_len(color_file),
        "visible_seed": str(visible_seed),
        "pair_group": str(pair_group),
        "actions": actions,
        "first_info": first_info,
        "last_info": last_info,
        "first_beads": first_beads,
        "last_beads": last_beads,
        "traj": traj,
        "color_path": str(color_path),
        "depth_path": str(depth_path),
        "success": bool(last_ex.get("task.done", False)),
        "final_fraction": as_float(final_fraction),
        "first_curve": curve_metric(first_beads),
        "final_curve": curve_metric(last_beads),
        "hidden_contact_meta": last_ex.get("hidden_contact_meta", {}),
        "hidden_condition_first": first_ex.get("hidden_condition", None),
        "hidden_condition_last": last_ex.get("hidden_condition", None),
    }


def load_all(data_root: Path) -> Dict[str, List[Dict]]:
    out: Dict[str, List[Dict]] = {}
    for cond in CONDITIONS:
        cond_dir = data_root / cond
        episodes = []
        for color_file in get_episode_files(cond_dir):
            try:
                episodes.append(load_episode(cond, cond_dir, color_file))
            except Exception as exc:
                print(f"[Phase2][WARN] failed to load {cond}/{color_file.name}: {exc}")
        out[cond] = episodes
    return out


def condition_summary(episodes_by_cond: Dict[str, List[Dict]]) -> List[Dict]:
    rows = []
    for cond in CONDITIONS:
        eps = episodes_by_cond.get(cond, [])
        rows.append(
            {
                "condition": cond,
                "episodes": len(eps),
                "success_rate": mean([e["success"] for e in eps]),
                "mean_final_fraction": mean([e["final_fraction"] for e in eps]),
                "mean_first_curve": mean([e["first_curve"] for e in eps]),
                "mean_final_curve": mean([e["final_curve"] for e in eps]),
                "std_final_curve": std([e["final_curve"] for e in eps]),
                "mean_episode_len": mean([e["episode_len"] for e in eps]),
            }
        )
    return rows


def trajectory_distance(traj_a: List[np.ndarray], traj_b: List[np.ndarray], start_idx: int = 0) -> Optional[float]:
    n = min(len(traj_a), len(traj_b))
    if n <= start_idx:
        return None
    vals = []
    for k in range(start_idx, n):
        d = chamfer_xy(traj_a[k], traj_b[k])
        if d is not None:
            vals.append(d)
    if not vals:
        return None
    return float(np.mean(vals))


def build_seed_index(episodes_by_cond: Dict[str, List[Dict]]) -> Dict[str, Dict[str, Dict]]:
    index: Dict[str, Dict[str, Dict]] = defaultdict(dict)
    for cond, eps in episodes_by_cond.items():
        for ep in eps:
            seed = str(ep["visible_seed"])
            if seed in {"", "None"}:
                continue
            if cond not in index[seed]:
                index[seed][cond] = ep
            else:
                # Keep first episode for this seed/condition.
                # Phase2 generator normally produces one episode per condition per seed.
                pass
    return dict(index)


def classify_branch(ep: Dict) -> str:
    cond = ep["condition"]
    success = bool(ep["success"])
    frac = ep.get("final_fraction")
    curve = ep.get("final_curve")

    if success:
        if cond == "hidden_high_friction":
            return "weak_contact_success"
        return "success_line"

    if cond == "hidden_pin":
        return "pinned_bend"

    if cond == "hidden_high_friction":
        return "friction_lag"

    return "failure_unknown"


def pair_record(
    seed: str,
    ep_a: Dict,
    ep_b: Dict,
    args: argparse.Namespace,
) -> Dict:
    init_ch = chamfer_xy(ep_a["first_beads"], ep_b["first_beads"])
    init_l2 = ordered_l2_xy(ep_a["first_beads"], ep_b["first_beads"])
    final_ch = chamfer_xy(ep_a["last_beads"], ep_b["last_beads"])
    final_l2 = ordered_l2_xy(ep_a["last_beads"], ep_b["last_beads"])
    traj_ch = trajectory_distance(ep_a["traj"], ep_b["traj"], start_idx=1)

    act_d = action_history_distance(ep_a["actions"], ep_b["actions"], prefix_actions=1)

    color_a = load_initial_color_for_episode(ep_a)
    color_b = load_initial_color_for_episode(ep_b)
    rgb = arr_stats_absdiff(color_a, color_b)
    del color_a, color_b

    depth_a = load_initial_depth_for_episode(ep_a)
    depth_b = load_initial_depth_for_episode(ep_b)
    depth = arr_stats_absdiff(depth_a, depth_b)
    del depth_a, depth_b
    gc.collect()

    contact_diff = ep_a["condition"] != ep_b["condition"]
    success_diff = bool(ep_a["success"] != ep_b["success"])

    visible_pass = (
        init_ch is not None
        and init_ch <= args.tau_vis
        and rgb["mean_abs"] is not None
        and rgb["mean_abs"] <= args.tau_rgb_mean
        and depth["mean_abs"] is not None
        and depth["mean_abs"] <= args.tau_depth_mean
    )
    action_pass = act_d is not None and act_d <= args.tau_action
    contact_pass = bool(contact_diff)
    future_metric = final_ch if final_ch is not None else traj_ch
    future_pass = future_metric is not None and future_metric >= args.tau_future

    ccda_state = bool(visible_pass and action_pass and contact_pass and future_pass)
    ccda_success = bool(ccda_state and success_diff)

    return {
        "visible_seed": seed,
        "condition_a": ep_a["condition"],
        "condition_b": ep_b["condition"],
        "file_a": ep_a["file"],
        "file_b": ep_b["file"],
        "initial_chamfer": init_ch,
        "initial_ordered_l2": init_l2,
        "action_distance": act_d,
        "rgb_mean_abs_diff": rgb["mean_abs"],
        "rgb_max_abs_diff": rgb["max_abs"],
        "depth_mean_abs_diff": depth["mean_abs"],
        "depth_max_abs_diff": depth["max_abs"],
        "final_chamfer": final_ch,
        "final_ordered_l2": final_l2,
        "trajectory_chamfer": traj_ch,
        "contact_diff": contact_diff,
        "success_a": ep_a["success"],
        "success_b": ep_b["success"],
        "success_diff": success_diff,
        "final_fraction_a": ep_a["final_fraction"],
        "final_fraction_b": ep_b["final_fraction"],
        "final_curve_a": ep_a["final_curve"],
        "final_curve_b": ep_b["final_curve"],
        "branch_a": classify_branch(ep_a),
        "branch_b": classify_branch(ep_b),
        "visible_pass": visible_pass,
        "action_pass": action_pass,
        "contact_pass": contact_pass,
        "future_pass": future_pass,
        "ccda_state": ccda_state,
        "ccda_success": ccda_success,
        "failure_reason": failure_reason(visible_pass, action_pass, contact_pass, future_pass),
    }


def failure_reason(visible_pass: bool, action_pass: bool, contact_pass: bool, future_pass: bool) -> str:
    if visible_pass and action_pass and contact_pass and future_pass:
        return "ccda_state"
    if not visible_pass:
        return "visible_not_similar_or_rgbd_leakage"
    if not action_pass:
        return "action_not_similar"
    if not contact_pass:
        return "contact_not_different"
    if not future_pass:
        return "future_not_different"
    return "unknown"


def build_pair_records(seed_index: Dict[str, Dict[str, Dict]], args: argparse.Namespace) -> List[Dict]:
    records = []
    pair_order = [
        ("free", "hidden_pin"),
        ("free", "hidden_high_friction"),
        ("hidden_pin", "hidden_high_friction"),
    ]

    for seed, group in sorted(seed_index.items(), key=lambda kv: int(kv[0]) if kv[0].isdigit() else kv[0]):
        for a, b in pair_order:
            if a in group and b in group:
                records.append(pair_record(seed, group[a], group[b], args))

    return records


def ratio(records: List[Dict], key: str) -> Optional[float]:
    if not records:
        return None
    return float(np.mean([bool(r.get(key, False)) for r in records]))


def subset(records: List[Dict], **kwargs) -> List[Dict]:
    out = []
    for r in records:
        ok = True
        for k, v in kwargs.items():
            if r.get(k) != v:
                ok = False
                break
        if ok:
            out.append(r)
    return out


def pair_type(records: List[Dict], a: str, b: str) -> List[Dict]:
    return [
        r for r in records
        if r["condition_a"] == a and r["condition_b"] == b
    ]


def summarize_pairs(records: List[Dict]) -> Dict:
    ccda = [r for r in records if r["ccda_state"]]
    non = [r for r in records if not r["ccda_state"]]
    ccda_success = [r for r in records if r["ccda_success"]]

    by_pair = {}
    for a, b in [
        ("free", "hidden_pin"),
        ("free", "hidden_high_friction"),
        ("hidden_pin", "hidden_high_friction"),
    ]:
        rs = pair_type(records, a, b)
        by_pair[f"{a}_vs_{b}"] = {
            "count": len(rs),
            "ccda_state_ratio": ratio(rs, "ccda_state"),
            "ccda_success_ratio": ratio(rs, "ccda_success"),
            "success_diff_ratio": ratio(rs, "success_diff"),
            "mean_initial_chamfer": mean([r["initial_chamfer"] for r in rs]),
            "mean_action_distance": mean([r["action_distance"] for r in rs]),
            "mean_final_chamfer": mean([r["final_chamfer"] for r in rs]),
            "mean_trajectory_chamfer": mean([r["trajectory_chamfer"] for r in rs]),
            "mean_rgb_abs_diff": mean([r["rgb_mean_abs_diff"] for r in rs]),
            "mean_depth_abs_diff": mean([r["depth_mean_abs_diff"] for r in rs]),
        }

    ccda_successdiff_ratio = ratio(ccda, "success_diff")
    non_successdiff_ratio = ratio(non, "success_diff")

    if ccda_successdiff_ratio is None or non_successdiff_ratio is None:
        impact_gap = None
    else:
        impact_gap = ccda_successdiff_ratio - non_successdiff_ratio

    return {
        "total_pairs": len(records),
        "ccda_state_count": len(ccda),
        "ccda_state_ratio": ratio(records, "ccda_state"),
        "ccda_success_count": len(ccda_success),
        "ccda_success_ratio": ratio(records, "ccda_success"),
        "success_diff_ratio_all": ratio(records, "success_diff"),
        "success_diff_ratio_ccda_state": ccda_successdiff_ratio,
        "success_diff_ratio_non_ccda_state": non_successdiff_ratio,
        "ccda_impact_gap": impact_gap,
        "by_pair_type": by_pair,
        "failure_reason_counts": dict_count(records, "failure_reason"),
        "branch_pair_counts": branch_pair_counts(records),
    }


def dict_count(records: List[Dict], key: str) -> Dict[str, int]:
    out: Dict[str, int] = defaultdict(int)
    for r in records:
        out[str(r.get(key))] += 1
    return dict(out)


def branch_pair_counts(records: List[Dict]) -> Dict[str, int]:
    out: Dict[str, int] = defaultdict(int)
    for r in records:
        out[f"{r['branch_a']} vs {r['branch_b']}"] += 1
    return dict(out)


def rgbd_leakage_summary(records: List[Dict]) -> List[Dict]:
    rows = []
    for a, b in [
        ("free", "hidden_pin"),
        ("free", "hidden_high_friction"),
        ("hidden_pin", "hidden_high_friction"),
    ]:
        rs = pair_type(records, a, b)
        rows.append(
            {
                "pair": f"{a}_vs_{b}",
                "count": len(rs),
                "mean_rgb_abs_diff": mean([r["rgb_mean_abs_diff"] for r in rs]),
                "max_rgb_abs_diff": max_float([r["rgb_max_abs_diff"] for r in rs]),
                "mean_depth_abs_diff": mean([r["depth_mean_abs_diff"] for r in rs]),
                "max_depth_abs_diff": max_float([r["depth_max_abs_diff"] for r in rs]),
            }
        )
    return rows


def max_float(xs: Iterable[Any]) -> Optional[float]:
    vals = [as_float(x) for x in xs]
    vals = [x for x in vals if x is not None]
    if not vals:
        return None
    return float(np.max(vals))


def write_csv(path: Path, rows: List[Dict], fieldnames: Optional[List[str]] = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        keys = []
        seen = set()
        for row in rows:
            for k in row.keys():
                if k not in seen:
                    seen.add(k)
                    keys.append(k)
        fieldnames = keys

    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_report(path: Path, summary: Dict, cond_rows: List[Dict], rgbd_rows: List[Dict], records: List[Dict]) -> None:
    lines: List[str] = []

    lines.append("# Phase2 CCDA Audit Report")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Task: `{summary['task']}`")
    lines.append(f"- Data root: `{summary['data_root']}`")
    lines.append(f"- Conditions: `{', '.join(CONDITIONS)}`")
    lines.append(f"- Total paired comparisons: `{summary['pair_summary']['total_pairs']}`")
    lines.append(f"- CCDA-state count: `{summary['pair_summary']['ccda_state_count']}`")
    lines.append(f"- CCDA-state ratio: `{fmt(summary['pair_summary']['ccda_state_ratio'])}`")
    lines.append(f"- CCDA-success count: `{summary['pair_summary']['ccda_success_count']}`")
    lines.append(f"- CCDA-success ratio: `{fmt(summary['pair_summary']['ccda_success_ratio'])}`")
    lines.append(f"- CCDA impact gap: `{fmt(summary['pair_summary']['ccda_impact_gap'])}`")
    lines.append("")

    lines.append("## Thresholds")
    lines.append("")
    lines.append("| Metric | Threshold | Meaning |")
    lines.append("|---|---:|---|")
    for k, v in summary["thresholds"].items():
        lines.append(f"| `{k}` | `{v}` | |")
    lines.append("")

    lines.append("## Condition Summary")
    lines.append("")
    lines.append("| Condition | Episodes | Success Rate | Mean Final Fraction | Mean Final Curve |")
    lines.append("|---|---:|---:|---:|---:|")
    for row in cond_rows:
        lines.append(
            "| {} | {} | {} | {} | {} |".format(
                row["condition"],
                row["episodes"],
                fmt(row["success_rate"]),
                fmt(row["mean_final_fraction"]),
                fmt(row["mean_final_curve"]),
            )
        )
    lines.append("")

    lines.append("## Pair-Type Summary")
    lines.append("")
    lines.append("| Pair | Count | CCDA-State Ratio | CCDA-Success Ratio | SuccessDiff Ratio | Init Chamfer | Action Dist | Final Chamfer | RGB Mean Diff | Depth Mean Diff |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for pair, row in summary["pair_summary"]["by_pair_type"].items():
        lines.append(
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
                pair,
                row["count"],
                fmt(row["ccda_state_ratio"]),
                fmt(row["ccda_success_ratio"]),
                fmt(row["success_diff_ratio"]),
                fmt(row["mean_initial_chamfer"]),
                fmt(row["mean_action_distance"]),
                fmt(row["mean_final_chamfer"]),
                fmt(row["mean_rgb_abs_diff"]),
                fmt(row["mean_depth_abs_diff"]),
            )
        )
    lines.append("")

    lines.append("## RGB-D Leakage Check")
    lines.append("")
    lines.append("| Pair | Count | Mean RGB Abs Diff | Max RGB Abs Diff | Mean Depth Abs Diff | Max Depth Abs Diff |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for row in rgbd_rows:
        lines.append(
            "| {} | {} | {} | {} | {} | {} |".format(
                row["pair"],
                row["count"],
                fmt(row["mean_rgb_abs_diff"]),
                fmt(row["max_rgb_abs_diff"]),
                fmt(row["mean_depth_abs_diff"]),
                fmt(row["max_depth_abs_diff"]),
            )
        )
    lines.append("")

    lines.append("## Failure Reason Counts")
    lines.append("")
    lines.append("| Reason | Count |")
    lines.append("|---|---:|")
    for k, v in sorted(summary["pair_summary"]["failure_reason_counts"].items()):
        lines.append(f"| `{k}` | {v} |")
    lines.append("")

    lines.append("## Branch Pair Counts")
    lines.append("")
    lines.append("| Branch Pair | Count |")
    lines.append("|---|---:|")
    for k, v in sorted(summary["pair_summary"]["branch_pair_counts"].items()):
        lines.append(f"| `{k}` | {v} |")
    lines.append("")

    lines.append("## Top CCDA-Success Examples")
    lines.append("")
    lines.append("| Seed | Pair | Init Chamfer | Action Dist | Final Chamfer | Success A | Success B | Branch A | Branch B |")
    lines.append("|---|---|---:|---:|---:|---:|---:|---|---|")
    examples = [r for r in records if r["ccda_success"]]
    examples = sorted(examples, key=lambda r: as_float(r["final_chamfer"]) or 0, reverse=True)[:20]
    for r in examples:
        lines.append(
            "| {} | {} vs {} | {} | {} | {} | {} | {} | {} | {} |".format(
                r["visible_seed"],
                r["condition_a"],
                r["condition_b"],
                fmt(r["initial_chamfer"]),
                fmt(r["action_distance"]),
                fmt(r["final_chamfer"]),
                r["success_a"],
                r["success_b"],
                r["branch_a"],
                r["branch_b"],
            )
        )
    lines.append("")

    lines.append("## Phase2 Conclusion")
    lines.append("")
    free_pin = summary["pair_summary"]["by_pair_type"].get("free_vs_hidden_pin", {})
    thresholds = summary["thresholds"]
    free_pin_pass = (
        (free_pin.get("ccda_state_ratio") or 0.0) >= 0.7
        and (free_pin.get("ccda_success_ratio") or 0.0) >= 0.5
        and (free_pin.get("mean_initial_chamfer") or float("inf")) <= thresholds["tau_vis_initial_chamfer"]
        and (free_pin.get("mean_action_distance") or float("inf")) <= thresholds["tau_action_first_action"]
        and (free_pin.get("mean_final_chamfer") or 0.0) >= thresholds["tau_future_final_chamfer"]
        and (free_pin.get("mean_rgb_abs_diff") or float("inf")) <= thresholds["tau_rgb_mean_abs_diff"]
        and (free_pin.get("mean_depth_abs_diff") or float("inf")) <= thresholds["tau_depth_mean_abs_diff"]
    )
    if free_pin_pass:
        lines.append(
            "Phase2 confirms a formal CCDA dataset for `hidden-contact-cable-line`: "
            "the `free` and `hidden_pin` paired rollouts keep matched visible initial state, "
            "matched first action, and RGB-D observations below the leakage thresholds, while "
            "their future cable states and success outcomes diverge."
        )
    else:
        lines.append(
            "Phase2 does not yet satisfy the formal `free` vs `hidden_pin` CCDA acceptance thresholds. "
            "Inspect the pair metrics above before using this dataset as CCDA evidence."
        )
    lines.append("")
    lines.append(
        "Phase2 keeps only two hidden-contact variants: `hidden_pin` and `hidden_high_friction`. "
        "`hidden_side_jam` remains removed because RGB-D observation checks showed visible leakage. "
        "The previous action-step observation replay visualization remains removed because it did not "
        "show continuous robot-cable contact and could be misleading. The retained visual checks are "
        "bead trajectory overlays and RGB-D observation checks. Continuous robot-cable interaction "
        "should be inspected only with the continuous PyBullet rollout recorder."
    )
    lines.append("")

    lines.append("## Interpretation")
    lines.append("")
    lines.append("- `CCDA-state` means visible state, RGB-D observation, and first action are similar, contact condition differs, and future cable state diverges.")
    lines.append("- `CCDA-success` additionally requires different success outcomes.")
    lines.append("- `hidden_pin` is expected to be the strong CCDA branch.")
    lines.append("- `hidden_high_friction` is retained as a weak-contact perturbation; it may show small future divergence without success difference.")
    lines.append("- If RGB-D differences are large, the hidden-contact premise is violated and the condition should not be used as CCDA evidence.")
    lines.append("")
    path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default="/data/state_diff2")
    parser.add_argument("--data_root", required=True)
    parser.add_argument("--task", default="hidden-contact-cable-line")
    parser.add_argument("--tau_vis", type=float, default=0.002)
    parser.add_argument("--tau_action", type=float, default=0.02)
    parser.add_argument("--tau_future", type=float, default=0.05)
    parser.add_argument("--tau_rgb_mean", type=float, default=1.0)
    parser.add_argument("--tau_depth_mean", type=float, default=1e-4)
    args = parser.parse_args()

    root = Path(args.root).resolve()
    data_root = Path(args.data_root).resolve()
    reports = root / "reports"
    reports.mkdir(parents=True, exist_ok=True)

    episodes_by_cond = load_all(data_root)

    for cond in CONDITIONS:
        if len(episodes_by_cond.get(cond, [])) == 0:
            raise SystemExit(f"[Phase2][FAIL] no episodes found for condition={cond} in {data_root / cond}")

    cond_rows = condition_summary(episodes_by_cond)
    seed_index = build_seed_index(episodes_by_cond)
    records = build_pair_records(seed_index, args)
    rgbd_rows = rgbd_leakage_summary(records)

    thresholds = {
        "tau_vis_initial_chamfer": args.tau_vis,
        "tau_action_first_action": args.tau_action,
        "tau_future_final_chamfer": args.tau_future,
        "tau_rgb_mean_abs_diff": args.tau_rgb_mean,
        "tau_depth_mean_abs_diff": args.tau_depth_mean,
    }

    summary = {
        "task": args.task,
        "data_root": str(data_root),
        "conditions": CONDITIONS,
        "thresholds": thresholds,
        "num_visible_seed_groups": len(seed_index),
        "condition_summary": cond_rows,
        "pair_summary": summarize_pairs(records),
    }

    out_json = reports / "phase2_ccda_audit_summary.json"
    out_md = reports / "phase2_ccda_audit_report.md"
    out_records_csv = reports / "phase2_ccda_records.csv"
    out_cond_csv = reports / "phase2_condition_summary.csv"
    out_rgbd_csv = reports / "phase2_rgbd_leakage_summary.csv"

    out_json.write_text(json.dumps(summary, indent=2, sort_keys=True))
    write_report(out_md, summary, cond_rows, rgbd_rows, records)
    write_csv(out_records_csv, records)
    write_csv(out_cond_csv, cond_rows)
    write_csv(out_rgbd_csv, rgbd_rows)

    print(json.dumps(summary, indent=2, sort_keys=True))
    print("[Phase2] wrote", out_json)
    print("[Phase2] wrote", out_md)
    print("[Phase2] wrote", out_records_csv)
    print("[Phase2] wrote", out_cond_csv)
    print("[Phase2] wrote", out_rgbd_csv)

    if len(records) == 0:
        raise SystemExit("[Phase2][FAIL] no pair records generated")

    # Soft validation. Do not fail if hidden_high_friction is weak.
    free_pin = summary["pair_summary"]["by_pair_type"].get("free_vs_hidden_pin", {})
    if free_pin.get("count", 0) == 0:
        raise SystemExit("[Phase2][FAIL] no free-vs-hidden_pin pairs")

    if (free_pin.get("ccda_success_ratio") or 0.0) < 0.5:
        raise SystemExit(
            "[Phase2][FAIL] free-vs-hidden_pin ccda_success_ratio < 0.5. "
            "Task does not yet provide strong CCDA-success evidence."
        )


if __name__ == "__main__":
    main()
