"""PB0-S REV4: robustness audit for the Wiring-post hidden descriptor.

This is an offline qualification phase over the frozen PB0 rollout dataset.
It does not change the formal PB0 verdict and does not run a simulator.

The main question is whether the 27,569 REV3 "original hidden" pairs are
supported by a robust routing difference or are primarily generated by the
binary 3 mm contact-like proxy changing value near its threshold.

Important non-claims:
- a geometric contact proxy is not physical contact;
- a large threshold margin is not proof of physical contact;
- a small margin is not proof that a pair is physically identical;
- no future-divergence or sensor signal is used to rank the shortlist.
"""
from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import subprocess
import sys

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.experiment3.dlolab_wiring_post.screening_audit_rev3 import (  # noqa: E402
    load_json,
    scan_observation_hidden_pairs,
)


def git(*args):
    return subprocess.check_output(
        ["git", *args],
        cwd=REPO_ROOT,
        text=True,
    ).strip()


def stats(values):
    values = list(values)
    if not values:
        return {
            "n": 0,
            "min": None,
            "p01": None,
            "p05": None,
            "median": None,
            "p95": None,
            "p99": None,
            "max": None,
        }
    x = np.asarray(values, dtype=np.float64)
    return {
        "n": int(x.size),
        "min": float(np.min(x)),
        "p01": float(np.percentile(x, 1)),
        "p05": float(np.percentile(x, 5)),
        "median": float(np.percentile(x, 50)),
        "p95": float(np.percentile(x, 95)),
        "p99": float(np.percentile(x, 99)),
        "max": float(np.max(x)),
    }


def replay_locator(rollout_id, n_envs_per_batch, base_seed):
    rollout_id = int(rollout_id)
    n_envs = int(n_envs_per_batch)
    batch_index = rollout_id // n_envs
    env_index = rollout_id % n_envs
    return {
        "rollout_id": rollout_id,
        "batch_index": int(batch_index),
        "env_index": int(env_index),
        "batch_seed": int(base_seed) + int(batch_index),
    }


def contact_proxy_metrics(
        descriptor,
        contact_threshold_m,
        deadbands_m,
        roi_wrap_threshold_rad,
        global_angle_threshold_rad):
    threshold = float(contact_threshold_m)
    desc_a = descriptor["descriptor_a"]
    desc_b = descriptor["descriptor_b"]

    mismatch_posts = []
    for post_index, (first, second) in enumerate(zip(desc_a, desc_b)):
        contact_a = bool(first["contact_like"])
        contact_b = bool(second["contact_like"])
        if contact_a == contact_b:
            continue

        clearance_a = float(first["surface_clearance_m"])
        clearance_b = float(second["surface_clearance_m"])
        low = min(clearance_a, clearance_b)
        high = max(clearance_a, clearance_b)

        lower_side_margin = max(0.0, threshold - low)
        upper_side_margin = max(0.0, high - threshold)
        symmetric_boundary_margin = min(
            lower_side_margin,
            upper_side_margin,
        )

        mismatch_posts.append({
            "post_index": int(post_index),
            "clearance_a_m": clearance_a,
            "clearance_b_m": clearance_b,
            "threshold_m": threshold,
            "threshold_separation_width_m": float(high - low),
            "lower_side_margin_m": float(lower_side_margin),
            "upper_side_margin_m": float(upper_side_margin),
            "symmetric_boundary_margin_m":
                float(symmetric_boundary_margin),
            "threshold_interval_center_offset_m":
                float(0.5 * (low + high) - threshold),
        })

    max_roi_wrap = max(
        [float(v) for v in descriptor["roi_wrap_difference_rad"]],
        default=0.0,
    )
    max_global_angle = max(
        [float(v) for v in descriptor["global_angular_difference_rad"]],
        default=0.0,
    )

    nearest_vertex_delta = max(
        [
            abs(
                int(a["nearest_vertex"])
                - int(b["nearest_vertex"])
            )
            for a, b in zip(desc_a, desc_b)
        ],
        default=0,
    )

    has_contact_mismatch = bool(mismatch_posts)
    has_original_wrap_support = bool(
        max_roi_wrap >= float(roi_wrap_threshold_rad)
    )
    has_global_angle_support = bool(
        max_global_angle >= float(global_angle_threshold_rad)
    )

    if has_contact_mismatch and has_original_wrap_support:
        reason = "contact_and_original_wrap"
    elif has_original_wrap_support:
        reason = "original_wrap_only"
    elif has_contact_mismatch:
        reason = "contact_proxy_only"
    else:
        reason = "other"

    max_symmetric_margin = max(
        [
            row["symmetric_boundary_margin_m"]
            for row in mismatch_posts
        ],
        default=0.0,
    )
    max_width = max(
        [
            row["threshold_separation_width_m"]
            for row in mismatch_posts
        ],
        default=0.0,
    )

    deadband_survival = {}
    for deadband in deadbands_m:
        deadband = float(deadband)
        survives = any(
            row["lower_side_margin_m"] >= deadband
            and row["upper_side_margin_m"] >= deadband
            for row in mismatch_posts
        )
        deadband_survival[
            "{:.9f}".format(deadband)
        ] = bool(survives)

    return {
        "reason": reason,
        "has_contact_proxy_mismatch": has_contact_mismatch,
        "has_original_wrap_support": has_original_wrap_support,
        "has_global_angle_support_diagnostic": has_global_angle_support,
        "max_roi_wrap_difference_rad": float(max_roi_wrap),
        "max_global_angular_difference_rad": float(max_global_angle),
        "max_nearest_vertex_index_delta": int(nearest_vertex_delta),
        "max_symmetric_boundary_margin_m":
            float(max_symmetric_margin),
        "max_threshold_separation_width_m":
            float(max_width),
        "mismatch_posts": mismatch_posts,
        "deadband_survival": deadband_survival,
    }


def candidate_row(
        pair,
        metrics,
        replay_cfg):
    return {
        "rollout_a": int(pair["rollout_a"]),
        "rollout_b": int(pair["rollout_b"]),
        "time_index": int(pair["time_index"]),
        "observable_chamfer_m":
            float(pair["observable_chamfer_m"]),
        "ee_position_distance_m":
            float(pair["ee_position_distance_m"]),
        "hidden_robustness": metrics,
        "replay_a": replay_locator(
            pair["rollout_a"],
            replay_cfg["n_envs_per_batch"],
            replay_cfg["base_seed"],
        ),
        "replay_b": replay_locator(
            pair["rollout_b"],
            replay_cfg["n_envs_per_batch"],
            replay_cfg["base_seed"],
        ),
    }


def deadband_sensitivity_rows(
        deadbands_m,
        deadband_counts,
        reason_counts,
        n_original_hidden):
    n_original_hidden = int(n_original_hidden)
    n_contact_proxy_supported = int(
        reason_counts.get("contact_proxy_only", 0)
        + reason_counts.get("contact_and_original_wrap", 0)
    )

    rows = []
    for deadband in deadbands_m:
        deadband = float(deadband)
        key = "{:.9f}".format(deadband)
        count = int(deadband_counts.get(key, 0))
        rows.append({
            "symmetric_deadband_m": deadband,
            "surviving_count": count,
            "surviving_fraction_of_original_hidden":
                float(count / n_original_hidden)
                if n_original_hidden else None,
            "surviving_fraction_of_contact_proxy_supported":
                float(count / n_contact_proxy_supported)
                if n_contact_proxy_supported else None,
        })

    return n_contact_proxy_supported, rows


def analyze_pairs(
        original_hidden_pairs,
        pb0_cfg,
        rev4_cfg):
    oracle = pb0_cfg["oracle_pair_descriptor"]
    robustness = rev4_cfg["robustness"]
    threshold = float(
        robustness["contact_proxy_threshold_m"]
    )
    configured_original_threshold = float(
        oracle["contact_proxy_margin_m"]
    )
    if not np.isclose(
            threshold,
            configured_original_threshold,
            rtol=0.0,
            atol=1e-12):
        raise RuntimeError(
            "REV4 contact threshold must equal the frozen PB0 "
            "contact_proxy_margin_m"
        )

    deadbands = [
        float(v)
        for v in robustness["symmetric_deadband_sweep_m"]
    ]
    roi_threshold = float(
        oracle["wrap_difference_min_rad"]
    )
    global_threshold = float(
        rev4_cfg["source_global_angle_threshold_rad"]
    )

    rows = []
    reason_counter = Counter()
    time_counter = Counter()
    deadband_counts = Counter()

    symmetric_margins = []
    threshold_widths = []
    roi_wrap_values = []
    global_angle_values = []
    nearest_vertex_deltas = []

    for pair in original_hidden_pairs:
        metrics = contact_proxy_metrics(
            pair["hidden_descriptor_diagnostic"],
            threshold,
            deadbands,
            roi_threshold,
            global_threshold,
        )
        row = candidate_row(
            pair,
            metrics,
            rev4_cfg["replay"],
        )
        rows.append(row)

        reason_counter[
            metrics["reason"]
        ] += 1
        time_counter[
            int(pair["time_index"])
        ] += 1

        if metrics["has_contact_proxy_mismatch"]:
            symmetric_margins.append(
                metrics[
                    "max_symmetric_boundary_margin_m"
                ]
            )
            threshold_widths.append(
                metrics[
                    "max_threshold_separation_width_m"
                ]
            )

        roi_wrap_values.append(
            metrics[
                "max_roi_wrap_difference_rad"
            ]
        )
        global_angle_values.append(
            metrics[
                "max_global_angular_difference_rad"
            ]
        )
        nearest_vertex_deltas.append(
            metrics[
                "max_nearest_vertex_index_delta"
            ]
        )

        for key, survives in metrics[
                "deadband_survival"
            ].items():
            if survives:
                deadband_counts[key] += 1

    n = len(rows)

    (
        contact_proxy_supported_pair_count,
        deadband_sweep,
    ) = deadband_sensitivity_rows(
        deadbands,
        deadband_counts,
        reason_counter,
        n,
    )

    top_k = int(
        robustness["top_k"]
    )

    top_by_margin = sorted(
        [
            row for row in rows
            if row["hidden_robustness"][
                "has_contact_proxy_mismatch"
            ]
        ],
        key=lambda row: (
            -row["hidden_robustness"][
                "max_symmetric_boundary_margin_m"
            ],
            row["observable_chamfer_m"],
        ),
    )[:top_k]

    top_by_width = sorted(
        [
            row for row in rows
            if row["hidden_robustness"][
                "has_contact_proxy_mismatch"
            ]
        ],
        key=lambda row: (
            -row["hidden_robustness"][
                "max_threshold_separation_width_m"
            ],
            row["observable_chamfer_m"],
        ),
    )[:top_k]

    routing_supported = sorted(
        [
            row for row in rows
            if row["hidden_robustness"][
                "has_original_wrap_support"
            ]
        ],
        key=lambda row: (
            -row["hidden_robustness"][
                "max_roi_wrap_difference_rad"
            ],
            row["observable_chamfer_m"],
        ),
    )

    top_by_global_angle = sorted(
        rows,
        key=lambda row: (
            -row["hidden_robustness"][
                "max_global_angular_difference_rad"
            ],
            row["observable_chamfer_m"],
        ),
    )[:top_k]

    return {
        "pair_count": int(n),
        "reason_counts": {
            key: int(value)
            for key, value
            in sorted(reason_counter.items())
        },
        "contact_proxy_supported_pair_count":
            contact_proxy_supported_pair_count,
        "time_index_counts": {
            str(key): int(value)
            for key, value
            in sorted(time_counter.items())
        },
        "contact_proxy_symmetric_boundary_margin_m":
            stats(symmetric_margins),
        "contact_proxy_threshold_separation_width_m":
            stats(threshold_widths),
        "max_roi_wrap_difference_rad":
            stats(roi_wrap_values),
        "max_global_angular_difference_rad":
            stats(global_angle_values),
        "max_nearest_vertex_index_delta":
            stats(nearest_vertex_deltas),
        "symmetric_deadband_sensitivity":
            deadband_sweep,
        "original_wrap_supported_pair_count":
            int(len(routing_supported)),
        "global_angle_supported_pair_count_diagnostic":
            int(sum(
                row["hidden_robustness"][
                    "has_global_angle_support_diagnostic"
                ]
                for row in rows
            )),
        "top_by_contact_symmetric_boundary_margin":
            top_by_margin,
        "top_by_contact_threshold_separation_width":
            top_by_width,
        "original_wrap_supported_pairs":
            routing_supported[:top_k],
        "top_by_global_angle_difference_diagnostic":
            top_by_global_angle,
    }


def build_shortlist(
        analysis,
        rev4_cfg):
    k = int(
        rev4_cfg["robustness"]["committed_shortlist_k"]
    )

    if analysis[
        "original_wrap_supported_pair_count"
    ] > 0:
        source = "original_wrap_supported_pairs"
        purpose = (
            "Candidate states for snapshot same-action validation. "
            "Selection uses current-state routing evidence only."
        )
        rows = analysis[
            "original_wrap_supported_pairs"
        ][:k]
    else:
        source = (
            "top_by_contact_symmetric_boundary_margin"
        )
        purpose = (
            "Candidates for targeted physical-contact validation only. "
            "They are NOT qualified CCDA pairs and must not be sent "
            "directly to formal Gate 4 solely because of this ranking."
        )
        rows = analysis[
            "top_by_contact_symmetric_boundary_margin"
        ][:k]

    return {
        "selection_source": source,
        "selection_uses_future_divergence": False,
        "selection_uses_robot_force_or_sensor_signal": False,
        "purpose": purpose,
        "candidates": rows,
    }


def findings_and_next_action(
        analysis):
    findings = [
        "PB0S_REV4_ORIGINAL_HIDDEN_DESCRIPTOR_DECOMPOSED"
    ]

    reason = analysis[
        "reason_counts"
    ]
    contact_only = int(
        reason.get(
            "contact_proxy_only",
            0,
        )
    )
    original_wrap = int(
        analysis[
            "original_wrap_supported_pair_count"
        ]
    )

    if contact_only > 0:
        findings.append(
            "PB0S_REV4_CONTACT_PROXY_CONTRIBUTES_TO_HIDDEN_PAIR_SET"
        )

    if original_wrap > 0:
        findings.append(
            "PB0S_REV4_ORIGINAL_WRAP_SUPPORTED_PAIRS_EXIST"
        )
        next_action = (
            "Use the original-wrap-supported shortlist for a targeted "
            "snapshot same-action multi-horizon audit. The snapshot phase "
            "must compare inter-pair divergence against deterministic "
            "repeat/uncertainty at each horizon."
        )
    else:
        findings.append(
            "PB0S_REV4_NO_ORIGINAL_WRAP_SUPPORTED_PAIRS_DETECTED"
        )
        next_action = (
            "Do not send contact-proxy-only pairs directly to formal Gate 4. "
            "Use the margin-ranked shortlist for a small targeted replay that "
            "first checks whether a genuine simulator-native DLO-post "
            "contact/coupling signal can be obtained from the pinned DLO-Lab "
            "implementation at the candidate timestep. Only physically "
            "confirmed hidden-state "
            "differences should proceed to snapshot same-action branching. "
            "If a stable physical contact readout cannot be obtained, do not "
            "promote the 3 mm proxy to ground truth; move to a published task "
            "with a cleaner privileged interaction state."
        )

    return findings, next_action


def build_report(
        rev4_cfg,
        analysis,
        shortlist):
    findings, next_action = findings_and_next_action(
        analysis
    )

    result = {
        "verdict":
            "PB0S_REV4_HIDDEN_DESCRIPTOR_ROBUSTNESS_AUDITED",
        "formal_pb0_verdict":
            rev4_cfg["source"]["formal_pb0_verdict"],
        "formal_pb0_verdict_changed": False,
        "new_simulator_rollout": False,
        "model_training_started": False,
        "findings": findings,
        "analysis": analysis,
        "shortlist": shortlist,
        "next_action": next_action,
        "non_claims": [
            "The binary 3 mm contact-like proxy is not physical contact ground truth.",
            "A large proxy margin is not proof of physical contact.",
            "A small proxy margin is not proof of physical equivalence.",
            "The shortlist is ranked without future divergence or sensor signals.",
            "No threshold from the deadband sweep is promoted to a new formal gate.",
        ],
    }

    raw_root = Path(
        rev4_cfg["outputs"]["raw_root"]
    )
    raw_root.mkdir(
        parents=True,
        exist_ok=True,
    )
    (raw_root / "HIDDEN_DESCRIPTOR_ROBUSTNESS.json").write_text(
        json.dumps(result, indent=2) + "\n",
        encoding="utf-8",
    )
    (raw_root / "CANDIDATE_SHORTLIST.json").write_text(
        json.dumps(shortlist, indent=2) + "\n",
        encoding="utf-8",
    )

    committed = (
        REPO_ROOT
        / rev4_cfg["outputs"]["committed_report_dir"]
    )
    committed.mkdir(
        parents=True,
        exist_ok=True,
    )

    evidence = {
        "phase_name": rev4_cfg["phase_name"],
        "verdict": result["verdict"],
        "repository": {
            "starting_main_sha":
                rev4_cfg["provenance"]["starting_main_sha"],
            "ending_main_sha": git("rev-parse", "HEAD"),
            "dlolab_gitlink":
                git("rev-parse", "HEAD:external/dlo-lab"),
        },
        "scientific": result,
    }
    (committed / "EVIDENCE.json").write_text(
        json.dumps(evidence, indent=2) + "\n",
        encoding="utf-8",
    )
    (committed / "CANDIDATE_SHORTLIST.json").write_text(
        json.dumps(shortlist, indent=2) + "\n",
        encoding="utf-8",
    )

    reason = analysis["reason_counts"]
    margin = analysis[
        "contact_proxy_symmetric_boundary_margin_m"
    ]
    width = analysis[
        "contact_proxy_threshold_separation_width_m"
    ]

    lines = [
        "# PB0-S REV4 Wiring-post Hidden Descriptor Robustness",
        "",
        "Verdict: `PB0S_REV4_HIDDEN_DESCRIPTOR_ROBUSTNESS_AUDITED`",
        "",
        "Formal PB0 verdict remains: `{}`".format(
            result["formal_pb0_verdict"]
        ),
        "",
        "## Pair decomposition",
        "",
        "- Original hidden pairs: {}".format(
            analysis["pair_count"]
        ),
        "- contact-proxy-only: {}".format(
            reason.get("contact_proxy_only", 0)
        ),
        "- original-wrap-only: {}".format(
            reason.get("original_wrap_only", 0)
        ),
        "- contact + original-wrap: {}".format(
            reason.get("contact_and_original_wrap", 0)
        ),
        "- Original-wrap-supported total: {}".format(
            analysis["original_wrap_supported_pair_count"]
        ),
        "",
        "## Contact-proxy threshold robustness",
        "",
        "- Symmetric boundary margin median: {}".format(
            margin["median"]
        ),
        "- Symmetric boundary margin p95: {}".format(
            margin["p95"]
        ),
        "- Symmetric boundary margin max: {}".format(
            margin["max"]
        ),
        "- Threshold-separation width median: {}".format(
            width["median"]
        ),
        "- Threshold-separation width max: {}".format(
            width["max"]
        ),
        "",
        "The full deadband sensitivity curve is in EVIDENCE.json. "
        "No deadband value is promoted to a new gate.",
        "",
        "## Shortlist",
        "",
        "- Source: `{}`".format(
            shortlist["selection_source"]
        ),
        "- Future divergence used for selection: No",
        "- Robot force/sensor used for selection: No",
        "- Candidate count: {}".format(
            len(shortlist["candidates"])
        ),
        "",
        "## Findings",
        "",
    ]
    lines.extend(
        "- `{}`".format(item)
        for item in findings
    )
    lines.extend([
        "",
        "## Next action",
        "",
        next_action,
        "",
    ])
    (committed / "RESULT.md").write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    return result


def run(config_path):
    rev4_cfg = load_json(config_path)

    pb0_cfg = load_json(
        REPO_ROOT
        / rev4_cfg["source"]["pb0_config"]
    )
    rev3_cfg = load_json(
        REPO_ROOT
        / rev4_cfg["source"]["rev3_config"]
    )

    # The diagnostic global-angle threshold must remain the REV3 value.
    rev4_cfg = dict(rev4_cfg)
    rev4_cfg[
        "source_global_angle_threshold_rad"
    ] = float(
        rev3_cfg["descriptor_diagnostics"][
            "global_angular_difference_min_rad"
        ]
    )

    dataset_path = Path(
        rev4_cfg["source"]["dataset"]
    )
    if not dataset_path.is_file():
        raise FileNotFoundError(
            str(dataset_path)
        )

    with np.load(dataset_path) as data:
        scan = scan_observation_hidden_pairs(
            data,
            pb0_cfg,
            rev3_cfg,
        )

    original_hidden_pairs = scan[
        "original_hidden_pairs"
    ]
    expected = int(
        rev4_cfg["source"][
            "expected_original_hidden_pair_count"
        ]
    )
    if len(original_hidden_pairs) != expected:
        raise RuntimeError(
            "REV4 did not reproduce REV3 original-hidden pair count: "
            "{} != {}".format(
                len(original_hidden_pairs),
                expected,
            )
        )

    analysis = analyze_pairs(
        original_hidden_pairs,
        pb0_cfg,
        rev4_cfg,
    )
    shortlist = build_shortlist(
        analysis,
        rev4_cfg,
    )
    return build_report(
        rev4_cfg,
        analysis,
        shortlist,
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        required=True,
    )
    args = parser.parse_args()
    result = run(args.config)
    print(
        "verdict={}".format(
            result["verdict"]
        )
    )
    for finding in result["findings"]:
        print(
            "finding={}".format(
                finding
            )
        )


if __name__ == "__main__":
    main()
